version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7.3

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
